### ISSUE TITLE
Add an option to not generate images larger than the source

### ISSUE THREAD

**Issue by Maistho** [TrigenSoftware/gulp-srcset#1]
Currently when I generate images, if I have a really small image (lets say it's a `150x150px` profile pic) I will get a bunch of images that are still `150x150px` but have `@560w` etc. at the end.

I'm thinking that it would be nice if the plugin checked how large the image is and didn't generate an image if the source is smaller than the target.

I do a similar thing in my [gulp-html-transform plugin](https://github.com/Maistho/gulp-html-transform/blob/master/src/plugins/srcset/srcset.ts#L84) which works really well.

#### Would you be interested in a PR implementing this as an option?

Thanks for this really useful plugin!

**Comment by dangreen** [comment]
@Maistho can you provide gulp-task example, to understand exactly what you mean?

**Comment by dangreen** [comment]
@Maistho 
```js
gulp.task('images', () =>
	gulp.src('src/*.{jpg,png,gif,ico}')
		// do not resize images smaller than 150px in width
		.pipe(srcset([{
			match:  '(max-width: 150px)',
			format: [...]
		}], [{
			match:  '(min-width: 151px)',
			width:  [...],
			format: [...]
		}]))
		.pipe(gulp.dest('dist'))
);
```
?

**Comment by dangreen** [comment]
@Maistho okay, I will add this feature today.

**Comment by dangreen** [comment]
@Maistho https://github.com/TrigenSoftware/gulp-srcset#boolean-optionsscalingup

**Comment by Maistho** [comment]
Wonderful, thanks!
